altran_filter_node:
  ros__parameters:
    use_sim_time: false
    topics:
      publisher:
        gnss: "/aorta/car_info/filtered/altran/gnss"
        trajectory: "/aorta/trajectory/filtered/altran"
        objects: "/aorta/car_info/filtered/altran/objects"
      subscriber:
        trajectory: "/aorta/trajectory/altran"
        gnss: "/aorta/car_info/altran/gnss"
        objects: "/aorta/car_info/altran/objects"
    communication:
      objects:
        drop_probability: 0.0
        delay_probability: 0.0
        delay_time_ms: 0
      trajectory:
        drop_probability: 0.0
        delay_probability: 0.0
        delay_time_ms: 0
      
