aorta_server_node:
  ros__parameters:
    use_sim_time: false
    topics:
      publisher:
        # Trajectory publishers are important see
        # the trajectory part
        trajectory:
          altran: "/aorta/trajectory/altran"
          akka: "/aorta/trajectory/akka"
          tuk: "/aorta/trajectory/tuk"
          default: "/aorta/trajectory/default"
          emergency: "/aorta/trajectory/emergency"
        traffic_light: "/aorta/control/traffic_light/program"
      subscriber:
        gnss:
          altran: "/aorta/car_info/filtered/altran/gnss"
          akka: "/aorta/car_info/filtered/akka/gnss"
          tuk: "/aorta/car_info/filtered/tuk/gnss"
        object_list:
          altran: "/aorta/car_info/filtered/altran/objects"
          akka: "/aorta/car_info/filtered/akka/objects"
          tuk: "/aorta/car_info/filtered/tuk/objects"
        edge: "/aorta/edge/objects"
        traffic_light: "/carla/traffic_lights/status"
    trajectory:
      # If you add a trajectory then define a publisher
      # otherwise the node will log two warnings
      altran: [140.0, -2.0, 150.0, -4.0]
      akka: [134.0, -2.0, 140.0, -5.0]
      tuk: [128.0, -2.0, 132.0, -5.0]
      default: [122.0, -2.0, 126.0, -7.0]
      emergency: [110.0, -2.0, 120.0, 1.0, 160.0, 1.0, 180.0, -2.0]
      
